#before_script:
#  - apt-get update
#  - apt-get install -qq git curl libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev
#  - apt-get install zlib1g-dev libzip-dev
#  - apt-get clean
#  - docker-php-ext-install pdo_mysql zip
#  - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#  - php artisan serve
#
#image: php:7.3
#
#services:
#  - mysql:5.7
#
#variables:
#  MYSQL_ROOT_PASSWORD: secret
#  MYSQL_DATABASE: homestead
#  MYSQL_USER: homestead
#  MYSQL_PASSWORD: secret
#  DB_HOST: mysql
#  DB_USERNAME: root
#
#stages:
#  - test
#
#browser_test:
#  stage: test
#  # image: chilio/laravel-dusk-ci:latest
#  script:
#    - echo "Starting pest tests"
#    - composer install
#    - php artisan dusk:install
#    - php artisan
#    # - configure-laravel
#    # - start-nginx-ci-project
#    - cp .env.test .env
#    - php artisan key:generate
#    - php artisan migrate
#    - vendor/bin/pest
#    -
#
#
#
#variables:
#  MYSQL_ROOT_PASSWORD: secret
#  MYSQL_DATABASE: homestead
#  MYSQL_USER: homestead
#  MYSQL_PASSWORD: secret
#  DB_HOST: mysql
#  DB_USERNAME: root

stages:
  - test

test:
  stage: test
  services:
    - mysql:5.7
  image: chilio/laravel-dusk-ci:latest
  script:
    - echo "Starting pest tests"
    - composer install
    - configure-laravel
    - start-nginx-ci-project
    - cp .env.test .env
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/pest




