before_script:
  - apt-get clean
  - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

image: php:7.3

services:
  - mysql:5.7
  - php:7.3

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root


stages:
  - test

browser_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - vendor/bin/pest


